### ISSUE TITLE
(Mix) Could not start application, returned an error: shutdown: failed to start child: Boltx

### ISSUE THREAD

**Issue by aakashjhawar** [sagastume/boltx#44]
I've added Boltx to my Supervision tree.

Config:
```
config :boltx, Bolt,
  uri: System.get_env("NEO4J_HOST") || "bolt://localhost:7687",
  auth: [username: "neo4j", password: System.get_env("NEO4J_PASSWORD") || "password"],
  user_agent: "boltxTest/1",
  pool_size: 15,
  max_overflow: 3,
  prefix: :default
```

`application.ex`
```
%{
       id: Boltx,
       start: {Boltx, :start_link, Application.get_env(:boltx, Bolt)}
}
```

While starting the server, I got the following error.

```
** (Mix) Could not start application accounts_service: AccountsService.Application.start(:normal, []) returned an error: shutdown: failed to start child: Boltx
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Boltx.start_link/6 is undefined or private
            (boltx 0.0.3) Boltx.start_link({:uri, "bolt://localhost:7687"}, {:auth, [username: "neo4j", password: "password"]}, {:user_agent, "boltxTest/1"}, {:pool_size, 15}, {:max_overflow, 3}, {:prefix, :default})
            (stdlib 3.17.2) supervisor.erl:414: :supervisor.do_start_child_i/3
            (stdlib 3.17.2) supervisor.erl:400: :supervisor.do_start_child/2
            (stdlib 3.17.2) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 3.17.2) supervisor.erl:1250: :supervisor.children_map/4
            (stdlib 3.17.2) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Can you please check this, and suggest a better way to add Boltx to the application supervisor?

**Comment by sagastume** [comment]
Thanks for reporting.

It should work, I'll check and send a fix :smiley:

**Comment by sagastume** [comment]
I have been reviewing and noticed that, when refactoring Bolt Sips, I removed the functionality as an application. Initially, Boltx was designed as a library with the intention of creating an adapter for Ecto, similar to how postgrex, myxql, and ecto_sql do.

However, at that time, it doesn't make much sense to not provide an adapter or application. Therefore, I plan to initiate a minimal adapter in this repository to later migrate it to a standalone repository.

This would be the minimum needed to integrate it into an application, like Bolt_Sips does.

**Comment by sagastume** [comment]
I made a correction that prevents the process from starting and added documentation on how to integrate it into an application. The documentation is available in the README. A new version, v0.0.4, is now available.

You need to make two changes to your configuration. First, you have to add the 'name' key to be able to give a name to the process, and second, send the configuration as a list.

`application.ex`

```elixir
%{
  id: Boltx,
  start: {Boltx, :start_link, [Application.get_env(:boltx, Bolt)] },
}
````

`config.ex`

```elixir
config :boltx, Bolt,
  uri: "bolt://localhost:7687",
  auth: [username: "neo4j", password: "password"],
  user_agent: "boltxTest/1",
  pool_size: 15,
  max_overflow: 3,
  prefix: :default,
  name: Boltx
````

Then you can use it like this:

```elixir
iex> Boltx.query!(Boltx, "return 1 as n") |> Boltx.Response.first()
%{"n" => 1}
````
