### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by tiagodavi** [sagastume/boltx#57]
Great work here! Thank you for adding support for Neo4j v5!

I've created this library [Ex4j](https://github.com/tiagodavi/ex4j) recently to add support for better abstractions on Neo4j instead of writing strings manually to retrieve data (it reminds 1990's) as well as being able to wrap the response in a struct similar to ecto.

I intend to replace `bolt.sips` with your driver that seems better and support the newer versions.

**Comment by sagastume** [comment]
Thanks to you, @tiagodavi .

I'm glad to hear that you want to use Boltx in your library. In fact, I was planning to send a PR to your library to integrate Boltx.

My intention in developing Boltx was to create the driver without additional abstractions, similar to how it was done with Postgrex, MyXQL, and Ecto SQL.

I'm glad that we can work together on this! If you need a hand with Ex4j or if there are things you want to change in Boltx, I'm here to help you.

**Comment by tiagodavi** [comment]
_"similar to how it was done with Postgrex"_ it makes total sense. 

I wanted to develop something similar to ecto on my library, but I had a hard time dealing with complex macros and dynamic binding, something like:

```elixir
match(User, as: :user)
|> where([user: u], u.age < 25)
|> return([user: u], u)
```

So I decided to simplify things and I think it's a bit better than writing those match, where, return and so on like a graphql query and I can also have the result wrapped in a structure, but I would love to have dynamic binding, mainly for filters like where clauses. 

As soon as I add your lib I will let you know. 

Thank you.

**Comment by sagastume** [comment]
Your library is great!

I hope to contribute as well. For now, I will close that topic. Thank you

**Comment by marcnnn** [comment]
@tiagodavi how is the progress of Ex4j to use boltx?

**Comment by tiagodavi** [comment]
Hi @marcnnn, I’ve had to pause working on this as I haven’t had the time to continue. I’ve been juggling quite a lot lately.
