### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by tlemens** [sagastume/boltx#75]
First of all, thank you for your great work on boltx. 

In my organization [EnBW](https://github.com/EnBWAG) we are working on a project where we use Elixir and Neo4j. This week we switched to boltx.

We have been thinking about how we can support the development of boltx (e.g. contributing or co-maintaining). Do you have any thoughts on this? 

Kind regards

**Comment by sagastume** [comment]
Of course. It's great to know that you are using Boltx.
I'd really like you to be a co-maintainer to make sure the project stays more active. At the moment, I have a rather vague roadmap, but we could refine it. Broadly speaking, it's as follows:

- Improve the code (with the help of Credo).
- Fix small bugs to better adapt to the bolt protocol.
- Achieve 80 percent test coverage
- Running tests with Benchee to improve performance
- Adaptation to Ecto (with another library, Boltx-Ecto)

Other changes planned for a major release
- Refactor types and adapt API to be similar to official drivers (Relationship, Path, UnboundRelationship, etc.)
- Bookmark manager

**Comment by sagastume** [comment]
Hello everyone! I want to share an update on this issue.

I've been reflecting on some rules for those who wish to be maintainers or contributors to the project, and I've come to these conclusions:

1. It is necessary to have contributed at least 5 times consistently, and those contributions have become part of a version.
2. All Pull Requests (PRs) must be approved by me, as well as by other collaborators/maintainers of the project.

Additionally, all contributions from forks are welcome, as long as the PRs are concise. If the PRs contain a lot of code and are difficult to analyze and understand, they will be rejected, and contributors will be asked to submit contributions in more manageable pieces.

There are other ways to contribute to the project:

1. Reporting bugs.
2. Proposing use cases to be covered by tests.
3. Adding documentation.
5. They can also contribute in other ways, such as becoming [sponsors](https://github.com/sponsors/sagastume) of the project.

For now, I will close this issue. Thank you very much to everyone for your contributions!
